import { Customer, Fee, Job, Invoice, Payment } from '@/types';

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Global Shipping Inc.',
    address: '123 Harbor Blvd, Port City, PC 12345',
    phone: '+1-555-0123',
    email: 'contact@globalshipping.com',
    taxId: 'TAX-001-2024',
    type: 'Company',
    notes: 'Premium customer, expedited processing',
    isActive: true,
    quickbooksCustomerId: 'QB-CUST-001',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Ocean Freight Ltd.',
    address: '456 Dock Street, Maritime City, MC 67890',
    phone: '+1-555-0456',
    email: 'info@oceanfreight.com',
    taxId: 'TAX-002-2024',
    type: 'Company',
    notes: 'Regular client, monthly billing',
    isActive: true,
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: 'John Anderson',
    address: '789 Trade Ave, Commerce Town, CT 34567',
    phone: '+1-555-0789',
    email: 'j.anderson@email.com',
    taxId: 'TAX-003-2024',
    type: 'Individual',
    notes: 'Individual importer, personal goods',
    isActive: true,
    createdAt: '2024-03-10',
  },
];

export const mockFees: Fee[] = [
  {
    id: '1',
    name: 'Port Charges',
    category: 'Port Services',
    defaultRate: 250,
    taxRate: 15,
    isTaxable: true,
    isActive: true,
    quickbooksItemId: 'QB-ITEM-001',
  },
  {
    id: '2',
    name: 'Customs Duty',
    category: 'Government Fees',
    defaultRate: 500,
    taxRate: 0,
    isTaxable: false,
    isActive: true,
    quickbooksItemId: 'QB-ITEM-002',
  },
  {
    id: '3',
    name: 'Documentation Fee',
    category: 'Administrative',
    defaultRate: 150,
    taxRate: 15,
    isTaxable: true,
    isActive: true,
  },
  {
    id: '4',
    name: 'Container Handling',
    category: 'Port Services',
    defaultRate: 300,
    taxRate: 15,
    isTaxable: true,
    isActive: true,
  },
  {
    id: '5',
    name: 'Storage Fee',
    category: 'Warehousing',
    defaultRate: 100,
    taxRate: 15,
    isTaxable: true,
    isActive: true,
  },
];

export const mockJobs: Job[] = [
  {
    id: '1',
    jobId: 'JOB-2024-001',
    dateOfReport: '2024-11-01',
    rotationNo: 'ROT-4523',
    shipperId: '1',
    consigneeId: '2',
    shipperAddress: '123 Harbor Blvd, Port City, PC 12345',
    consigneeAddress: '456 Dock Street, Maritime City, MC 67890',
    consigneeTel: '+1-555-0456',
    blNoAndType: 'BL-2024-7890 / Ocean',
    equipQtyAndType: '1 x 40ft Container',
    containerNo: 'CONT-4567890',
    sealNo: 'SEAL-123456',
    qtyAndPkgsDesc: '500 Cartons',
    cargoDescription: 'Electronics - Consumer Goods',
    grossWeight: '12,500 KG',
    measurement: '45 CBM',
    status: 'INVOICED',
    charges: [
      { id: '1', feeId: '1', feeName: 'Port Charges', amount: 250, taxAmount: 37.5, total: 287.5 },
      { id: '2', feeId: '2', feeName: 'Customs Duty', amount: 500, taxAmount: 0, total: 500 },
      { id: '3', feeId: '3', feeName: 'Documentation Fee', amount: 150, taxAmount: 22.5, total: 172.5 },
    ],
    createdAt: '2024-11-01',
  },
  {
    id: '2',
    jobId: 'JOB-2024-002',
    dateOfReport: '2024-11-05',
    rotationNo: 'ROT-4524',
    shipperId: '2',
    consigneeId: '3',
    shipperAddress: '456 Dock Street, Maritime City, MC 67890',
    consigneeAddress: '789 Trade Ave, Commerce Town, CT 34567',
    consigneeTel: '+1-555-0789',
    blNoAndType: 'BL-2024-7891 / Air',
    equipQtyAndType: '3 Pallets',
    containerNo: 'N/A',
    sealNo: 'N/A',
    qtyAndPkgsDesc: '150 Boxes',
    cargoDescription: 'Textile Materials',
    grossWeight: '1,800 KG',
    measurement: '8 CBM',
    status: 'OPEN',
    charges: [
      { id: '4', feeId: '1', feeName: 'Port Charges', amount: 250, taxAmount: 37.5, total: 287.5 },
      { id: '5', feeId: '4', feeName: 'Container Handling', amount: 300, taxAmount: 45, total: 345 },
    ],
    createdAt: '2024-11-05',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: '1',
    invoiceId: 'INV-2024-001',
    jobId: 'JOB-2024-001',
    customerId: '2',
    customerName: 'Ocean Freight Ltd.',
    issueDate: '2024-11-01',
    dueDate: '2024-11-30',
    currency: 'USD',
    total: 960,
    taxTotal: 60,
    amountPaid: 500,
    balance: 460,
    status: 'PARTIALLY_PAID',
    quickbooksInvoiceId: 'QB-INV-001',
    quickbooksSyncStatus: 'SYNCED',
    lines: [
      { id: '1', feeId: '1', description: 'Port Charges', quantity: 1, unitPrice: 250, taxRate: 15, lineTotal: 287.5 },
      { id: '2', feeId: '2', description: 'Customs Duty', quantity: 1, unitPrice: 500, taxRate: 0, lineTotal: 500 },
      { id: '3', feeId: '3', description: 'Documentation Fee', quantity: 1, unitPrice: 150, taxRate: 15, lineTotal: 172.5 },
    ],
  },
  {
    id: '2',
    invoiceId: 'INV-2024-002',
    jobId: 'JOB-2024-002',
    customerId: '3',
    customerName: 'John Anderson',
    issueDate: '2024-11-06',
    dueDate: '2024-12-06',
    currency: 'USD',
    total: 632.5,
    taxTotal: 82.5,
    amountPaid: 0,
    balance: 632.5,
    status: 'SENT',
    quickbooksSyncStatus: 'NOT_SYNCED',
    lines: [
      { id: '4', feeId: '1', description: 'Port Charges', quantity: 1, unitPrice: 250, taxRate: 15, lineTotal: 287.5 },
      { id: '5', feeId: '4', description: 'Container Handling', quantity: 1, unitPrice: 300, taxRate: 15, lineTotal: 345 },
    ],
  },
];

export const mockPayments: Payment[] = [
  {
    id: '1',
    paymentId: 'PAY-2024-001',
    invoiceId: 'INV-2024-001',
    customerId: '2',
    customerName: 'Ocean Freight Ltd.',
    date: '2024-11-10',
    amount: 500,
    method: 'Bank Transfer',
    reference: 'WIRE-789456',
    notes: 'Partial payment received',
    quickbooksPaymentId: 'QB-PAY-001',
  },
];
